#!/bin/bash

##############
# Word Rolls #
##############

# making script executable
# https://stackoverflow.com/a/5126052
# https://stackoverflow.com/a/12276562

# infinite loop
# https://www.cyberciti.biz/faq/bash-infinite-loop/
while true
do

	# take input
	# https://stackoverflow.com/a/9720193
	read -p "Enter a word: " word

	# replace spaces with hyphens
	# https://unix.stackexchange.com/a/212137
	wordWithHyphens=${word// /-}

	# lowercase
	# https://stackoverflow.com/a/2264537
	#word="${a,,}"
	#echo $word

	# sites
	oxfordLink="https://en.oxforddictionaries.com/definition/$wordWithHyphens"
	wordsInASentenceLink="https://wordsinasentence.com/$wordWithHyphens-in-a-sentence"
	dictionaryLink="https://www.dictionary.com/browse/$wordWithHyphens"

	# open in chrome
	# https://superuser.com/a/1148415
	open -a "Google Chrome" $oxfordLink $wordsInASentenceLink $dictionaryLink

	# open in dictionary
	# https://apple.stackexchange.com/a/90044
	open dict://"$word"

	# open photoshop
	open -a "Adobe Photoshop CS6"

done

# ~fin~ #
